language: go

sudo: required
services:
  - docker

os:
  - linux

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
      env:
        - GO111MODULE=on
        - DEPLOY=false
    - go: 1.13.x
      env:
        - GO111MODULE=on
        - DEPLOY=false
    - go: 1.14.x
      env:
        - GO111MODULE=on
        - DEPLOY=false
    - go: master
      env:
        - GO111MODULE=on
        - DEPLOY=false
  allow_failures:
    - go: master

git:
  depth: 10

addons:
  apt:
    packages:
      - docker-ce

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: env(DEPLOY) = true

before_install:
  - mkdir "${HOME}/go"; export GOPATH="${HOME}/go";
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.17.1

install:
  - go mod download
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"

go_import_path: github.com/theodesp/golangdocs.com

script:
  - make vet
  - make all
  - make image

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/25c09d04b5f62cb9b8ec
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
  on:
    branch: master
